# mysql: https://medium.com/@hamzaak/dockerize-mysql-with-docker-compose-4f1f789296e9
# elk: https://www.sarulabs.com/post/5/2019-08-12/sending-docker-logs-to-elasticsearch-and-kibana-with-filebeat.html
# promotheus & grafanna : https://github.com/weder96/SpringBootActuatorPrometheus.git

version: "3.2"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpass"
      MYSQL_ROOT_PASSWORD: "mysqlrootpass"
      MYSQL_DATABASE: "test"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-vol:/var/lib/mysql
    networks:
      - mysql-network

  department-service:
    container_name: department-service
    image: mettukiran070/department-service:1.0.0
    depends_on:
      - mysql
    command:
      - "java"
      - "-jar"
      - "/app.jar"
      - "--spring.datasource.url=jdbc:mysql://mysql:3306/test"
      - "--spring.datasource.username=root"
      - "--spring.datasource.password=mysqlrootpass"
    ports:
      - 8080:8080
    networks:
      - pg-network
      - mysql-network

  employee-service:
    container_name: employee-service
    image: mettukiran070/employee-service:1.0.0
    depends_on:
      - mysql
    command:
      - "java"
      - "-jar"
      - "/app.jar"
      - "--spring.datasource.url=jdbc:mysql://mysql:3306/test"
      - "--spring.datasource.username=root"
      - "--spring.datasource.password=mysqlrootpass"
    ports:
      - 8081:8081
    networks:
      - pg-network
      - mysql-network

  prometheus:
     image: prom/prometheus:latest
     container_name: prometheus
     volumes:
       - ./prometheus.yaml:/etc/prometheus/prometheus.yml
       - prometheus_data:/prometheus
     networks:
       - pg-network
     ports:
       - 9090:9090

  grafana:
     image: grafana/grafana:latest
     container_name: grafana
     depends_on:
       - prometheus
     ports:
       - 3000:3000
     networks:
       - pg-network

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.0"
    container_name: elasticsearch
    depends_on:
      - department-service
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.17.0"
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.17.0"
    container_name: filebeat
    user: root
    command: filebeat -e -strict.perms=false
    depends_on:
      - elasticsearch
    volumes:
      - ./filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  esdata:
    driver: local
  mysql-vol:
    driver: local
  prometheus_data:
     driver: local
networks:
  pg-network:
    driver: bridge
  mysql-network:
    driver: bridge

