# mysql: https://medium.com/@hamzaak/dockerize-mysql-with-docker-compose-4f1f789296e9
# elk: https://www.bogotobogo.com/DevOps/Docker/Docker_ELK_7_6_Elastic_Stack_Docker_Compose.php
# promotheus & grafanna : https://github.com/weder96/SpringBootActuatorPrometheus.git

version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpass"
      MYSQL_ROOT_PASSWORD: "mysqlrootpass"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-vol:/var/lib/mysql
    networks:
      - mysql-network

  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
     container_name: elasticsearch
     environment:
       - discovery.type=single-node
     ports:
       - 9200:9200
       - 9300:9300
     volumes:
       - esdata:/usr/share/elasticsearch/data
     networks:
       - elk-network

  logstash:
     image: docker.elastic.co/logstash/logstash:7.17.0
     container_name: logstash
     volumes:
       - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
     ports:
       - "5000:5000"
     depends_on:
       - elasticsearch
     networks:
       - elk-network

  kibana:
     image: docker.elastic.co/kibana/kibana:7.17.0
     container_name: kibana
     ports:
       - 5601:5601
     depends_on:
       - elasticsearch
       - logstash
     networks:
       - elk-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    container_name: filebeat
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./filebeat.yaml:/usr/share/filebeat/filebeat.yml
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    depends_on:
      - elasticsearch
    networks:
      - elk-network


  department-service:
    container_name: department-service
    image: mettukiran070/department-service:1.0.0
    depends_on:
      - mysql
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://logstash:12201"
    command:
      - "java"
      - "-jar"
      - "/app.jar"
      - "--spring.datasource.url=jdbc:mysql://mysql:3306/test"
    ports:
      - 8080:8080
    networks:
      - pg-network
      - mysql-network
      - elk-network

  employee-service:
    container_name: employee-service
    image: mettukiran070/employee-service:1.0.0
    depends_on:
      - mysql
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://logstash:12201"
    command:
      - "java"
      - "-jar"
      - "/app.jar"
      - "--spring.datasource.url=jdbc:mysql://mysql:3306/test"
    ports:
      - 8081:8081
    networks:
      - pg-network
      - mysql-network
      - elk-network

  prometheus:
     image: prom/prometheus:latest
     container_name: prometheus
     volumes:
       - ./prometheus.yaml:/etc/prometheus/prometheus.yml
       - prometheus_data:/prometheus
     networks:
       - pg-network
     ports:
       - 9090:9090

  grafana:
     image: grafana/grafana:latest
     container_name: grafana
     depends_on:
       - prometheus
     ports:
       - 3000:3000
     networks:
       - pg-network

volumes:
  mysql-vol:
    driver: local
  esdata:
    driver: local
  prometheus_data:
     driver: local
networks:
  elk-network:
    driver: bridge
  pg-network:
    driver: bridge
  mysql-network:
    driver: bridge

