# mysql: https://medium.com/@hamzaak/dockerize-mysql-with-docker-compose-4f1f789296e9
# elk: https://www.bogotobogo.com/DevOps/Docker/Docker_ELK_7_6_Elastic_Stack_Docker_Compose.php
# promotheus & grafanna : https://github.com/weder96/SpringBootActuatorPrometheus.git

version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpass"
      MYSQL_ROOT_PASSWORD: "mysqlrootpass"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-vol:/var/lib/mysql

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.17.0
  #   container_name: logstash
  #   volumes:
  #     - ./logstash-config:/usr/share/logstash/pipeline
  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.17.0
  #   container_name: kibana
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus
  #   networks:
  #     - aw-network
  #   ports:
  #     - 9090:9090
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - aw-network
volumes:
  mysql-vol:
    driver: local
  # esdata:
  #   driver: local
  # prometheus_data:
  #   driver: local
  # grafana_data:
  #   driver: local
# networks:
#   aw-network:
#     driver: bridge