scrape_configs:
  - job_name: 'department-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['department-service:8080']
        labels:
          application: 'department-service'