server:
  port: 8080

spring:
  application:
    name: department-service

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: mysqluser
    password: mysqlpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # Display the sql queries in the console

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["health", "prometheus", "metrics"]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true1
    prometheus:
      enabled: true

